Fix build issue update to C++23
Fix below build fail.
```
recipe-sysroot/usr/include/sdbusplus/asio/connection.hpp:88:32: error: 'move_only_function' in namespace 'std' does not name
a template type
|    88 |     using send_function = std::move_only_function<callback_t>;
```

Change-Id: Ib88e44e65facce5bb4497fdc82f07c94900e16cd
Signed-off-by: Vince Chang <vince_chang@aspeedtech.com>